### ISSUE TITLE
Public Fields should be UpperCase, wronganswer field is never used 

### ISSUE THREAD

**Issue by f-rakete** [silence2k6/QuizMaker#1]
https://github.com/silence2k6/QuizMaker/blob/b9667f5e06f26c28806d2ea1d67dd657a3d51c41/QuizCard.cs#L5-L7

**Comment by incredibleLeitman** [comment]
And "right" is misspelled you two dyslexics xD

**Comment by f-rakete** [comment]
> you two dyslexics xD

![image](https://user-images.githubusercontent.com/69428398/195200800-9c7a8361-ab04-445c-a1d7-94fb0c18ffbd.png)

**Comment by silence2k6** [comment]
done

**Comment by incredibleLeitman** [comment]
You should be able to close the issue from the github webage, if you think you are done 
![image](https://user-images.githubusercontent.com/24638443/195577758-a9cafdc2-cc03-4520-8df9-b08ffa5cb404.png)

Pls let us know if this does not work for you

Also, when setting an issue to "done" there should be a commit representing the solution. You can append a sharp and the issue number in the commit message and github will try to connect the commit to the issue,
for example for this issue your commit could look like 
"fix issue #1 by removing unused wrong answer field and fixing spelling error"
