### ISSUE TITLE
Writer and Reader are the same thing - do you need both? xD

### ISSUE THREAD

**Issue by f-rakete** [silence2k6/QuizMaker#2]
https://github.com/silence2k6/QuizMaker/blob/b9667f5e06f26c28806d2ea1d67dd657a3d51c41/Program.cs#L11-L12

**Comment by silence2k6** [comment]
probably not because you wouldn't have asked the question like this ^^ but I thought that sometimes I need only to read the backup harddrive and sometimes I just want to write on it....so I've splitted them.

**Comment by f-rakete** [comment]
> probably not because you wouldn't have asked the question like this ^^ but I thought that sometimes I need only to read the backup harddrive and sometimes I just want to write on it....so I've splitted them.

but you see that they are the exact same object `XmlSerializer(typeof(List<QuizCard>))` ^^ 

so there is really no need, one of those things can do both, load and save so you only need one. Call it serializer or something

**Comment by silence2k6** [comment]
done
