### ISSUE TITLE
Why is this called DataInterface? I'd say this is a plain old UI method :P

### ISSUE THREAD

**Issue by f-rakete** [silence2k6/QuizMaker#4]
https://github.com/silence2k6/QuizMaker/blob/b9667f5e06f26c28806d2ea1d67dd657a3d51c41/DataInterface.cs#L3-L32

**Comment by silence2k6** [comment]
I've done it in this class because this method creates new objects....means I'm getting new data which I need for my project.

**Comment by f-rakete** [comment]
> I've done it in this class because this method creates new objects....means I'm getting new data which I need for my project.

well that confuses me evern more - because thats the whole point of a UI method, to get new data. doesnt matter if that is a string or an object :D
