### ISSUE TITLE
Try to avoid CAPS_NAMES for parameters

### ISSUE THREAD

**Issue by f-rakete** [silence2k6/QuizMaker#6]
https://github.com/silence2k6/QuizMaker/blob/b9667f5e06f26c28806d2ea1d67dd657a3d51c41/UserInterface.cs#L107-L137

the reason to use them is for global values, if its an internal parameter just call it `maxQuestions` or whatever

**Comment by silence2k6** [comment]
you mean that I don't should use them do define method parameters with it (means should rename it) or that I shouldn't use them in generally as an input value for methods?

**Comment by f-rakete** [comment]
@silence2k6 not use them as parameter names (rename it ;) )

**Comment by silence2k6** [comment]
done
