### ISSUE TITLE
Nullable types

### ISSUE THREAD

**Issue by f-rakete** [silence2k6/QuizMaker#7]
https://github.com/silence2k6/QuizMaker/blob/b9667f5e06f26c28806d2ea1d67dd657a3d51c41/QuizMaker.csproj#L7

recommend disabling nullable types to get rid of all the warnings ;)

**Comment by silence2k6** [comment]
don't know how to put this in my code :(

**Comment by f-rakete** [comment]
> don't know how to put this in my code :(

There's a video for that :p

**Comment by silence2k6** [comment]
I can't find this video (just seen the video "What is NULL" but there is no explanation how to enable it)?!

**Comment by f-rakete** [comment]
if that is fixed why is there no commit?

(did you find the video?)
